export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Category } from "./Category";
export { default as AppLogo } from "./AppLogo";
export { default as MainContent } from "./MainContent";
export { default as Paper } from "./Paper";
export { default as Title } from "./Title";
export { default as Avatar } from "./Avatar";
export { default as BoatFlag } from "./BoatFlag";
